Fixed some nvim issues and some bash scripts issues

diff --git a/bash/scripts/bkp b/bash/scripts/bkp
--- a/bash/scripts/bkp
+++ b/bash/scripts/bkp
@@ -1,28 +1,28 @@
 #!/usr/bin/env bash
 
-    # TODO: Make this work when multiple paths are given
-    if [ ! $# -eq 1 ]; then
-        echo "More than one argument is currently not supported!" >&2
-        return 1
-    fi
+# TODO: Make this work when multiple paths are given
+if [ ! $# -eq 1 ]; then
+    echo "More than one argument is currently not supported!" >&2
+    exit 1
+fi
 
-    path=$1
-    if [ ! -e $path ]; then
-        echo "$path does not exist" >&2
-        return 1
-    fi
+path=$1
+if [ ! -e "$path" ]; then
+    echo "$path does not exist" >&2
+    exit 1
+fi
 
-    filename="$(basename "$path")"
-    directory="$(dirname "$path")"
-    new_filename_base="$filename.bkp"
-    if ! $(echo "$filename" | grep -o "^\."); then
-        new_filename_base=".$new_filename_base"
-    fi
+filename="$(basename "$path")"
+directory="$(dirname "$path")"
+new_filename_base="$filename.bkp"
+if ! eval "$(echo "$filename" | grep -o "^\.")"; then
+    new_filename_base=".$new_filename_base"
+fi
 
-    new_path="$directory/$new_filename_base-$(date +'%F_%R:%S')"
-    mv "$path" "$new_path" || {
-        echo "Failed to bkp $path to $new_path" >&2
-        return 1
-    }
+new_path="$directory/$new_filename_base-$(date +'%F_%R:%S')"
+mv "$path" "$new_path" || {
+    echo "Failed to bkp $path to $new_path" >&2
+    exit 1
+}
 
-    echo "Backed up $path to $new_path"
+echo "Backed up $path to $new_path"
diff --git a/bash/scripts/mklink b/bash/scripts/mklink
--- a/bash/scripts/mklink
+++ b/bash/scripts/mklink
@@ -1,43 +1,43 @@
 #!/usr/bin/env bash
 
-    if [ ! $# -eq 2 ]; then
-        echo "Only 2 arguments allowed when calling mklink" >&2
-        return 1
+if [ ! $# -eq 2 ]; then
+    echo "Only 2 arguments allowed when calling mklink" >&2
+    exit 1
+fi
+
+SED="$(which sed)" || {
+    echo "sed is not installed" >&2
+    exit 1
+}
+
+
+source=$(echo "$1" | $SED 's/\/$//')
+destination=$(echo "$2" | $SED 's/\/$//')
+
+if [ ! -e "$source" ]; then
+    echo "Source file $source does not exist" >&2
+    exit 1
+fi
+
+if [ -e "$destination" ]; then
+    bkp "$destination" || exit 1
+elif [ -L "$destination" ]; then
+    unlink "$destination" || exit 1
+fi
+
+if [ -d "$destination" ]; then
+    destination_directory="$destination"
+else
+    destination_directory="$(dirname "$destination")"
+    if [ ! -d "$destination_directory" ]; then
+        mkdir -p "$destination_directory" || {
+            echo "Failed to create directory"
+            exit 1
+        }
     fi
+fi
 
-    SED="$(which sed)" || {
-        echo "sed is not installed" >&2
-        return 1
-    }
-
-
-    source=$(echo "$1" | $SED 's/\/$//')
-    destination=$(echo "$2" | $SED 's/\/$//')
-    
-    if [ ! -e "$source" ]; then
-        echo "Source file $source does not exist" >&2
-        return 1
-    fi
-
-    if [ -e "$destination" ]; then
-        bkp "$destination" || return 1
-    elif [ -L "$destination" ]; then
-        unlink "$destination" || return 1
-    fi
-
-    if [ -d "$destination" ]; then
-        destination_directory="$destination"
-    else
-        destination_directory="$(dirname "$destination")"
-        if [ ! -d "$destination_directory" ]; then
-            mkdir -p "$destination_directory" || {
-                echo "Failed to create directory"
-                return 1
-            }
-        fi
-    fi
-
-    ln -s "$source" "$destination" || {
-        echo "Failed to link $source to $destination" >&2
-        return 1
-    }
+ln -s "$source" "$destination" || {
+    echo "Failed to link $source to $destination" >&2
+    exit 1
+}
diff --git a/bash/scripts/rst b/bash/scripts/rst
--- a/bash/scripts/rst
+++ b/bash/scripts/rst
@@ -1,29 +1,28 @@
 #!/usr/bin/env bash
-function rst() {
-    # TODO: Make this work when multiple paths are given
-    if [ ! $# -eq 1 ]; then
-        echo "More than one argument is currently not supported!" >&2
-        return 1
-    fi
 
-    path=$1
-    if [ ! -e $path ]; then
-        echo "$path does not exist" >&2
-        return 1
-    fi
+# TODO: Make this work when multiple paths are given
+if [ ! $# -eq 1 ]; then
+    echo "More than one argument is currently not supported!" >&2
+    exit 1
+fi
 
-    filename="$(basename "$path")"
-    directory="$(dirname "$path")"
-    new_path="$directory/$(echo $filename | grep -Po '(?<=\.).+(?=.bkp)')"
-    # Check if the new_path exists, if it does we will just run a bkp on it to
-    # get it out of the way
-    if [ -e "$new_path" ]; then
-        bkp "$new_path"
-    fi
-    mv "$path" "$new_path" || {
-        echo "Could not restore $path to $new_path" >&2
-        return 1
-    }
+path=$1
+if [ ! -e $path ]; then
+    echo "$path does not exist" >&2
+    exit 1
+fi
 
-    echo "Restored $path to $new_path"
+filename="$(basename "$path")"
+directory="$(dirname "$path")"
+new_path="$directory/$(echo $filename | grep -Po '(?<=\.).+(?=.bkp)')"
+# Check if the new_path exists, if it does we will just run a bkp on it to
+# get it out of the way
+if [ -e "$new_path" ]; then
+    bkp "$new_path"
+fi
+mv "$path" "$new_path" || {
+    echo "Could not restore $path to $new_path" >&2
+    exit 1
 }
+
+echo "Restored $path to $new_path"
